cat /dev/null > Day02First.txt
cat /dev/null > Day02FirstTests.txt
cat /dev/null > Day02SecondTests.txt
cat /dev/null > Day03First.txt
cat /dev/null > Day03FirstTests.txt
cat /dev/null > Day03SecondTests.txt
cat /dev/null > Day04First.txt
cat /dev/null > Day04FirstTests.txt
cat /dev/null > Day04SecondTests.txt
cat /dev/null > Day05First.txt
cat /dev/null > Day05FirstTests.txt
cat /dev/null > Day05SecondTests.txt
cat /dev/null > Day06First.txt
cat /dev/null > Day06FirstTests.txt
cat /dev/null > Day06SecondTests.txt
cat /dev/null > Day07First.txt
cat /dev/null > Day07FirstTests.txt
cat /dev/null > Day07SecondTests.txt
cat /dev/null > Day08First.txt
cat /dev/null > Day08FirstTests.txt
cat /dev/null > Day08SecondTests.txt
cat /dev/null > Day09First.txt
cat /dev/null > Day09FirstTests.txt
cat /dev/null > Day09SecondTests.txt
cat /dev/null > Day10First.txt
cat /dev/null > Day10FirstTests.txt
cat /dev/null > Day10SecondTests.txt
cat /dev/null > Day11First.txt
cat /dev/null > Day11FirstTests.txt
cat /dev/null > Day11SecondTests.txt
cat /dev/null > Day12First.txt
cat /dev/null > Day12FirstTests.txt
cat /dev/null > Day12SecondTests.txt
cat /dev/null > Day13First.txt
cat /dev/null > Day13FirstTests.txt
cat /dev/null > Day13SecondTests.txt
cat /dev/null > Day14First.txt
cat /dev/null > Day14FirstTests.txt
cat /dev/null > Day14SecondTests.txt
cat /dev/null > Day15First.txt
cat /dev/null > Day15FirstTests.txt
cat /dev/null > Day15SecondTests.txt
cat /dev/null > Day16First.txt
cat /dev/null > Day16FirstTests.txt
cat /dev/null > Day16SecondTests.txt
cat /dev/null > Day17First.txt
cat /dev/null > Day17FirstTests.txt
cat /dev/null > Day17SecondTests.txt
cat /dev/null > Day18First.txt
cat /dev/null > Day18FirstTests.txt
cat /dev/null > Day18SecondTests.txt
cat /dev/null > Day19First.txt
cat /dev/null > Day19FirstTests.txt
cat /dev/null > Day19SecondTests.txt
cat /dev/null > Day20First.txt
cat /dev/null > Day20FirstTests.txt
cat /dev/null > Day20SecondTests.txt
cat /dev/null > Day21First.txt
cat /dev/null > Day21FirstTests.txt
cat /dev/null > Day21SecondTests.txt
cat /dev/null > Day22First.txt
cat /dev/null > Day22FirstTests.txt
cat /dev/null > Day22SecondTests.txt
cat /dev/null > Day23First.txt
cat /dev/null > Day23FirstTests.txt
cat /dev/null > Day23SecondTests.txt
cat /dev/null > Day24First.txt
cat /dev/null > Day24FirstTests.txt
cat /dev/null > Day24SecondTests.txt
cat /dev/null > Day25First.txt
cat /dev/null > Day25FirstTests.txt
cat /dev/null > Day25SecondTests.txt
